// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.exception;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

public class ErrorResponse_setMessage_a4320850bf_Test {

    @InjectMocks
    private ErrorResponse errorResponse;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetMessage_Success() {
        String expectedMessage = "This is a test message";
        errorResponse.setMessage(expectedMessage);
        Assertions.assertEquals(expectedMessage, errorResponse.getMessage());
    }

    @Test
    public void testSetMessage_NullValue() {
        String expectedMessage = null;
        errorResponse.setMessage(expectedMessage);
        Assertions.assertNull(errorResponse.getMessage());
    }
}
