// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ErrorResponse_getErrorCode_1611122f8d_Test {

    private ErrorResponse errorResponse;

    @BeforeEach
    public void setUp() {
        errorResponse = new ErrorResponse();
    }

    @Test
    public void testGetErrorCode_Success() {
        errorResponse.setErrorCode(200);
        int expectedErrorCode = 200;
        int actualErrorCode = errorResponse.getErrorCode();
        assertEquals(expectedErrorCode, actualErrorCode, "Error code should be 200");
    }

    @Test
    public void testGetErrorCode_Failure() {
        errorResponse.setErrorCode(404);
        int expectedErrorCode = 500;
        int actualErrorCode = errorResponse.getErrorCode();
        assertEquals(expectedErrorCode, actualErrorCode, "Error code should be 500");
    }
}
