// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.exception;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

public class ErrorResponse_getMessage_cebf167bb8_Test {

    @Test
    public void testGetMessageSuccess() {
        // TODO: Replace "Expected Message" with the actual expected message
        String expectedMessage = "Expected Message";

        ErrorResponse errorResponse = Mockito.mock(ErrorResponse.class);
        Mockito.when(errorResponse.getMessage()).thenReturn(expectedMessage);

        String actualMessage = errorResponse.getMessage();

        Assertions.assertEquals(expectedMessage, actualMessage);
    }

    @Test
    public void testGetMessageFailure() {
        // TODO: Replace "Wrong Expected Message" with a message that is not expected to be returned
        String wrongExpectedMessage = "Wrong Expected Message";

        ErrorResponse errorResponse = Mockito.mock(ErrorResponse.class);
        // TODO: Replace "Actual Message" with the actual message that is expected to be returned
        Mockito.when(errorResponse.getMessage()).thenReturn("Actual Message");

        String actualMessage = errorResponse.getMessage();

        Assertions.assertNotEquals(wrongExpectedMessage, actualMessage);
    }
}
