// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.MockitoAnnotations;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class ErrorResponse_setErrorCode_026f9121a0_Test {

    @InjectMocks
    private ErrorResponse errorResponse;

    @BeforeEach
    public void setUp() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testSetErrorCode_positiveNumber() {
        int expectedErrorCode = 200;
        errorResponse.setErrorCode(expectedErrorCode);
        assertEquals(expectedErrorCode, errorResponse.getErrorCode());
    }

    @Test
    public void testSetErrorCode_zero() {
        int expectedErrorCode = 0;
        errorResponse.setErrorCode(expectedErrorCode);
        assertEquals(expectedErrorCode, errorResponse.getErrorCode());
    }

    @Test
    public void testSetErrorCode_negativeNumber() {
        int expectedErrorCode = -400;
        errorResponse.setErrorCode(expectedErrorCode);
        assertEquals(expectedErrorCode, errorResponse.getErrorCode());
    }
}
