// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.exception;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.springframework.boot.test.context.SpringBootTest;

import static org.junit.jupiter.api.Assertions.assertEquals;

@SpringBootTest
public class ToDoException_ToDoException_ed74048a3f_Test {

    @Mock
    private ToDoException toDoException;

    @BeforeEach
    public void setUp() throws Exception {
        toDoException = new ToDoException("Test Error Message");
    }

    @Test
    public void testToDoExceptionSuccess() {
        assertEquals("Test Error Message", toDoException.getMessage());
    }

    @Test
    public void testToDoExceptionFailure() {
        // TODO: Change the error message to trigger the test failure
        assertEquals("Different Error Message", toDoException.getMessage());
    }
}
