// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.exception;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class ToDoException_ToDoException_637f106845_Test {

    @Test
    public void testToDoException_DefaultConstructor() {
        ToDoException exception = new ToDoException();
        assertNull(exception.getMessage());
    }

    @Test
    public void testToDoException_MessageConstructor() {
        String testMessage = "Test message";
        ToDoException exception = new ToDoException(testMessage);
        assertEquals(testMessage, exception.getMessage());
    }
}
