// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example;

import com.example.model.ToDo;
import com.example.repository.ToDoRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.times;

public class DemoApplication_setup_78d6d6b3ac_Test {

    private DemoApplication demoApplication;
    private static final Logger logger = LoggerFactory.getLogger(DemoApplication.class);

    @Mock
    private ToDoRepository toDoRepository;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
        demoApplication = new DemoApplication();
    }

    @Test
    public void testSetupMethod() throws Exception {
        CommandLineRunner runner = demoApplication.setup(toDoRepository);
        runner.run();
        verify(toDoRepository, times(1)).save(new ToDo("Remove unused imports", true));
        verify(toDoRepository, times(1)).save(new ToDo("Clean the code", true));
        verify(toDoRepository, times(1)).save(new ToDo("Build the artifacts", false));
        verify(toDoRepository, times(1)).save(new ToDo("Deploy the jar file", true));
    }

    @Test
    public void testSetupMethodWithNoData() throws Exception {
        CommandLineRunner runner = demoApplication.setup(toDoRepository);
        runner.run();
        verify(toDoRepository, times(0)).save(new ToDo("No task", true));
    }
}
