// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.model;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

public class Response_Response_bdf3fa02b7_Test {

    private Response response;

    @BeforeEach
    public void setup() {
        response = new Response(200, "Success");
    }

    @Test
    public void testResponseConstructorSuccess() {
        assertEquals(200, response.getStatus());
        assertEquals("Success", response.getMessage());
    }

    @Test
    public void testResponseConstructorFailure() {
        Response errorResponse = new Response(404, "Not Found");
        assertEquals(404, errorResponse.getStatus());
        assertEquals("Not Found", errorResponse.getMessage());
    }
}
