// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Response_setMessage_a4320850bf_Test {

    private Response response;

    @BeforeEach
    public void setup() {
        response = new Response();
    }

    @Test
    public void testSetMessage_Success() {
        String expectedMessage = "Success";
        response.setMessage(expectedMessage);
        assertEquals(expectedMessage, response.getMessage());
    }

    @Test
    public void testSetMessage_Null() {
        String expectedMessage = null;
        response.setMessage(expectedMessage);
        assertEquals(expectedMessage, response.getMessage());
    }

    @Test
    public void testSetMessage_Empty() {
        String expectedMessage = "";
        response.setMessage(expectedMessage);
        assertEquals(expectedMessage, response.getMessage());
    }
}
