// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Response_setStatus_77df0e6923_Test {

    private Response response;

    @BeforeEach
    public void setup() {
        response = new Response();
    }

    @Test
    public void testSetStatusSuccess() {
        int expectedStatus = 200;
        response.setStatus(expectedStatus);
        assertEquals(expectedStatus, response.getStatus(), "The status should be set correctly");
    }

    @Test
    public void testSetStatusFailure() {
        int unexpectedStatus = 404;
        response.setStatus(200);
        assertNotEquals(unexpectedStatus, response.getStatus(), "The status should not be set to a wrong value");
    }
}
