// Test generated by RoostGPT for test go-test using AI Type Open AI and AI Model gpt-4

package com.example.model;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.junit.MockitoJUnitRunner;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

@RunWith(MockitoJUnitRunner.class)
public class ToDo_ToDo_caaa9cbe31_Test {

    private ToDo toDo;

    @Before
    public void setUp() {
        toDo = new ToDo(1L, "Test ToDo", false);
    }

    @Test
    public void testToDoConstructor() {
        assertNotNull(toDo);
        assertEquals(1L, toDo.getId());
        assertEquals("Test ToDo", toDo.getText());
        assertEquals(false, toDo.isCompleted());
    }

    @Test
    public void testToDoConstructorWithDifferentValues() {
        ToDo anotherToDo = new ToDo(2L, "Another Test ToDo", true);
        assertNotNull(anotherToDo);
        assertEquals(2L, anotherToDo.getId());
        assertEquals("Another Test ToDo", anotherToDo.getText());
        assertEquals(true, anotherToDo.isCompleted());
    }
}
